#!/bin/sh
 
usage()
{
	echo "0. clean up ./Buildit clean"
	echo "1. build 32bit program ./Buildit i386 [target in i386]"	
	echo "2. build 64bit program ./Buildit x64 [target in x64]"		
}
 
if [ "$*" = "clean" ] ; then
    make -f nbproject/Makefile-i386.mk QMAKE= SUBPROJECTS= .clean-conf
	make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .clean-conf
elif [ "$*" = "x64" ] ; then
    make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "i386" ] ; then
    make -f nbproject/Makefile-i386.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "hisiv100" ] ; then
    make -f nbproject/Makefile-hisiv100.mk QMAKE= SUBPROJECTS= .build-conf
else
    usage;
fi

